
# Redes Neuronales y Algoritmos Bioinspirados

# Optimización Heurística

## 1. Optimización Numérica

### 1.1. Función de Rosenbrock



La función de **Rosenbrock**, también conocida como "función del valle", es un estándar en
 la optimización matemática para evaluar algoritmos de optimización.


### Elección de los parámetros iniciales:

- **Tasa de aprendizaje (Learning rate -lrate):** Controla el tamaño del paso que da el algoritmo de descenso por gradiente en cada iteración mientras busca el mínimo de la función. Un valor pequeño asegura que el descenso sea gradual y no se "salte" el mínimo, pero un valor demasiado bajo puede hacer que el algoritmo tarde mucho en converger.
- **Número de iteraciones (epoch):**  Se refiere al número de pasos (actualizaciones) que realizará el algoritmo. En cada iteración, se calcula el gradiente de la función y se actualizan las coordenadas del punto.
- **Rango de inicialización (init_range):** Es el intervalo en el que se selecciona el punto de inicio para la optimización. Dado que el descenso por gradiente comienza desde un punto aleatorio, este parámetro define el rango dentro del cual se elige el valor inicial de las coordenadas. Se elige porque abarca una buena parte del espacio en el que se encuentra el mínimo global de la función de Rosenbrock, que está en el punto (1, 1).

**En 2 dimensiones:**

- Condiciones iniciales:
    - Coordenadas: Aleatoria
    - lrate (Tasa de aprendizaje):  0.002
    - Epoch (Iteraciones): 1000
    - Init_range (Rango de inicialización) : (-2, 2)





In [ ]:
# Función Rosembrock en 2D

import numpy as np
import matplotlib.pyplot as plt
import imageio

# Función de Rosenbrock
def rosenbrock(point):
    return ((1 - point[0])**2) + (100 * ((point[1] - point[0]**2)**2))

# Gradiente de la función de Rosenbrock
def rosenbrock_derivative(point):
    dx = -2 * (1 - point[0]) - 400 * point[0] * (point[1] - point[0]**2)
    dy = 200 * (point[1] - point[0]**2)
    return np.array([dx, dy])

# Visualización con coordenadas dinámicas en un recuadro
def visualize_2d_with_coordinates(ai, iteration, filename):
    x = np.linspace(-2, 2, 400)
    y = np.linspace(-1, 3, 400)
    X, Y = np.meshgrid(x, y)
    Z = ((1 - X)**2) + (100 * ((Y - X**2)**2))

    ai = np.array(ai)
    trajectory_x = ai[:, 0]
    trajectory_y = ai[:, 1]

    plt.figure(figsize=(10, 7))
    plt.contourf(X, Y, Z, levels=50, cmap='viridis')
    plt.colorbar(label='Función de Rosenbrock')
    plt.plot(trajectory_x, trajectory_y, color='red', marker='o', markersize=2, label='Trayectoria')

    # Mostrar coordenadas en un recuadro
    current_x, current_y = trajectory_x[-1], trajectory_y[-1]
    plt.text(1.5, 2.5, f"Iteración: {iteration}\nX: {current_x:.4f}\nY: {current_y:.4f}",
             fontsize=10, color='white', bbox=dict(facecolor='black', alpha=0.7),
             verticalalignment='top', horizontalalignment='right')

    # Etiqueta del mínimo global
    plt.scatter(1, 1, color='blue', label='Mínimo global', zorder=5)
    plt.title("Descenso por gradiente en la función de Rosenbrock (2D)")
    plt.xlabel("X")
    plt.ylabel("Y")
    plt.legend()
    plt.savefig(filename)
    plt.close()

# Función principal
def main():
    dimensions = 2
    lrate = 0.002
    epoch = 1000
    init_range = (-2, 2)

    a = np.random.uniform(-0.24387705, 0.37539017, dimensions)
    print(f"Condición inicial: {a}")

    ai = []
    filenames = []

    for i in range(epoch):
        f = rosenbrock(a)
        ai.append(np.append(a, f))
        grad = rosenbrock_derivative(a)
        a = a - lrate * grad

        # Guardar imagen cada 5 iteraciones o en la última
        if i % 5 == 0 or i == epoch - 1:
            filename = f"frame_{i}.png"
            visualize_2d_with_coordinates(ai, i, filename)
            filenames.append(filename)

        if np.linalg.norm(grad) < 1e-6:
            print(f"Convergencia alcanzada en iteración {i}.")
            break

    # Crear GIF con loop infinito
    with imageio.get_writer('descenso_gradiente_recuadro.gif', mode='I', duration=0.2) as writer:
        for filename in filenames:
            image = imageio.imread(filename)
            writer.append_data(image)

    print("GIF creado: descenso_gradiente_recuadro.gif")

if __name__ == '__main__':
    main()



Condición inicial: [ 0.14423124 -0.20495984]


<ipython-input-2-feeb4bbf67c9>:80: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(filename)


GIF creado: descenso_gradiente_recuadro.gif


**En tres dimensiones:**
- Condiciones iniciales:
    - Coordenadas: Aleatoria
    - lrate (Tasa de aprendizaje):  0.002
    - Epoch (Iteraciones): 1000
    - Init_range (Rango de inicialización) : (-2, 2)

In [ ]:
# Función Rosembrock en 3D

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import imageio

# Función de Rosenbrock en 3D
def rosenbrock(point):
    return ((1 - point[0])**2) + (100 * ((point[1] - point[0]**2)**2)) + \
           ((1 - point[1])**2) + (100 * ((point[2] - point[1]**2)**2))

# Gradiente de la función de Rosenbrock en 3D
def rosenbrock_derivative(point):
    dx = -2 * (1 - point[0]) - 400 * point[0] * (point[1] - point[0]**2)
    dy = -2 * (1 - point[1]) - 400 * point[1] * (point[2] - point[1]**2) + 200 * (point[1] - point[0]**2)
    dz = 200 * (point[2] - point[1]**2)
    return np.array([dx, dy, dz])

# Visualización en 3D con coordenadas dinámicas
def visualize_3d_with_coordinates(ai, iteration, filename):
    ai = np.array(ai)
    trajectory_x = ai[:, 0]
    trajectory_y = ai[:, 1]
    trajectory_z = ai[:, 2]

    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')

    # Graficar trayectoria
    ax.plot3D(trajectory_x, trajectory_y, trajectory_z, color='red', label='Trayectoria')
    ax.scatter3D(trajectory_x, trajectory_y, trajectory_z, color='red', s=5)

    # Punto actual
    current_x, current_y, current_z = trajectory_x[-1], trajectory_y[-1], trajectory_z[-1]
    ax.scatter3D(current_x, current_y, current_z, color='orange', s=50, label='Punto actual')

    # Coordenadas actuales en texto
    ax.text2D(0.1, 0.9, f"Iteración: {iteration}\nX: {current_x:.4f}\nY: {current_y:.4f}\nZ: {current_z:.4f}",
              transform=fig.transFigure, fontsize=10, color='black', bbox=dict(facecolor='white', alpha=0.8))

    # Mínimo global
    ax.scatter3D(1, 1, 1, color='blue', s=50, label='Mínimo global')
    ax.text(1, 1, 1.1, '(1.00, 1.00, 1.00)', color='blue', fontsize=10)

    # Etiquetas y leyendas
    ax.set_title("Descenso por gradiente en la función de Rosenbrock (3D)", fontsize=12)
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.legend()
    plt.savefig(filename)
    plt.close()

# Función principal
def main():
    dimensions = 3
    lrate = 0.002
    epoch = 1000
    init_range = (-2, 2)

    a = np.random.uniform(init_range[0], init_range[1], dimensions)
    print(f"Condición inicial: {a}")

    ai = []
    filenames = []

    for i in range(epoch):
        f = rosenbrock(a)
        ai.append(np.append(a, f))
        grad = rosenbrock_derivative(a)
        a = a - lrate * grad

        # Guardar imagen cada 5 iteraciones o en la última
        if i % 5 == 0 or i == epoch - 1:
            filename = f"frame_{i}.png"
            visualize_3d_with_coordinates(ai, i, filename)
            filenames.append(filename)

        if np.linalg.norm(grad) < 1e-6:
            print(f"Convergencia alcanzada en iteración {i}.")
            break

    # Crear GIF
    with imageio.get_writer('descenso_gradiente_3D_recuadro.gif', mode='I', duration=0.2, loop=0) as writer:
        for filename in filenames:
            image = imageio.imread(filename)
            writer.append_data(image)

    print("GIF creado: descenso_gradiente_3D_recuadro.gif")

if __name__ == '__main__':
    main()



Condición inicial: [-0.75791617 -0.5482016  -0.43639041]


<ipython-input-17-86b0b40cfd3c>:87: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(filename)


GIF creado: descenso_gradiente_3D_recuadro.gif


### 1.2. Función Rastrigin

**En 2 dimensiones**
  - Condiciones iniciales:
      - Coordenadas: Aleatorias
      - lrate (Tasa de aprendizaje): 0.01
      - Epoch (Iteraciones): 1000
      - Init_range (Rango de inicialización) : (-5.12, 5.12)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import imageio

# Función de Rastrigin
def rastrigin(point):
    """
    Calcula el valor de la función de Rastrigin.
    Args:
        point (array-like): Punto donde se evalúa la función.
    Returns:
        float: Valor de la función en el punto dado.
    """
    A = 10
    return A * len(point) + sum([(x**2 - A * np.cos(2 * np.pi * x)) for x in point])

# Derivada de la función de Rastrigin
def rastrigin_derivative(point):
    """
    Calcula el gradiente de la función de Rastrigin.
    Args:
        point (array-like): Punto donde se evalúa el gradiente.
    Returns:
        array: Gradiente de la función en el punto dado.
    """
    A = 10
    return np.array([2 * x + 2 * np.pi * A * np.sin(2 * np.pi * x) for x in point])

# Visualización en 2D con cuadro informativo
def visualize_rastrigin_2d(ai, iteration, filename=None):
    """
    Genera un gráfico en 2D mostrando la trayectoria del descenso por gradiente
    en la función de Rastrigin.
    Args:
        ai (list): Lista de puntos visitados durante el descenso.
        iteration (int): Iteración actual para mostrar en el gráfico.
        filename (str): Nombre del archivo si se quiere guardar la imagen.
    """
    ai = np.array(ai)
    trajectory_x = ai[:, 0]
    trajectory_y = ai[:, 1]

    x = np.linspace(-5.12, 5.12, 400)
    y = np.linspace(-5.12, 5.12, 400)
    X, Y = np.meshgrid(x, y)
    Z = 10 * 2 + (X**2 - 10 * np.cos(2 * np.pi * X)) + (Y**2 - 10 * np.cos(2 * np.pi * Y))

    fig, ax = plt.subplots(figsize=(8, 6))
    ax.contourf(X, Y, Z, 50, cmap='viridis')
    ax.plot(trajectory_x, trajectory_y, color='red', marker='o', markersize=3, label='Trayectoria')

    # Etiqueta del mínimo global
    ax.scatter(0, 0, color='blue', label='Mínimo global', s=50)
    ax.text(0, 0, '(0, 0)', fontsize=10, color='blue')

    # Cuadro informativo
    text_str = (
        f"Iteración: {iteration}\n"
        f"Coordenadas: ({ai[-1, 0]:.2f}, {ai[-1, 1]:.2f})\n"
        f"Valor: {ai[-1, -1]:.4f}\n"
        f"Mínimo global: (0, 0)"
    )
    plt.gcf().text(0.02, 0.85, text_str, fontsize=10, color='black', bbox=dict(facecolor='white', alpha=0.8))

    ax.set_title("Descenso por gradiente en la función de Rastrigin (2D)")
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.legend()

    if filename:
        plt.savefig(filename)
    plt.close()

# Función principal: Descenso por gradiente
def main():
    """
    Realiza el descenso por gradiente en la función de Rastrigin.
    """
    # Configuración de parámetros
    dimensions = 2  # Dimensiones: cambiar a 2
    lrate = 0.01  # Tasa de aprendizaje
    epoch = 1000  # Número de iteraciones
    init_range = (-5.12, 5.12)  # Rango para punto inicial

    # Generar punto inicial
    a = np.random.uniform(init_range[0], init_range[1], dimensions)
    print(f"Condición inicial: {a}")

    # Registrar los puntos visitados
    ai = []
    images = []

    for i in range(epoch):
        # Evaluar la función objetivo
        f = rastrigin(a)
        ai.append(np.append(a, f))

        # Calcular el gradiente y actualizar el punto
        grad = rastrigin_derivative(a)
        a = a - lrate * grad

        # Guardar imágenes para el GIF cada 10 iteraciones
        if i % 10 == 0:
            filename = f"rastrigin_2d_iter_{i}.png"
            visualize_rastrigin_2d(ai, iteration=i, filename=filename)
            images.append(imageio.imread(filename))

        # Verificar convergencia
        if np.linalg.norm(grad) < 1e-6:
            print(f"Convergencia alcanzada en iteración {i}.")
            break

    ai = np.array(ai)

    # Resultados
    print("Últimos pasos:")
    print(ai[-10:, :])
    print(f"Mínimo alcanzado: {ai[-1, :-1]} con valor {ai[-1, -1]}")

    # Crear GIF con loop infinito
    imageio.mimsave('descenso_rastrigin_2d.gif', images, fps=5, loop=0)
    print("GIF generado: descenso_rastrigin_2d.gif")

if __name__ == '__main__':
    main()


Condición inicial: [ 1.20996398 -3.65540751]


<ipython-input-14-74af9a591746>:106: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  images.append(imageio.imread(filename))


Últimos pasos:
[[ 1.05656431 -2.69564277 22.35711135]
 [ 0.81679754 -3.23375747 26.03069078]
 [ 1.37424879 -2.54403298 45.01798802]
 [ 0.90038342 -2.66477833 24.90982449]
 [ 1.25046645 -3.15185694 25.74411329]
 [ 0.59714128 -2.57622514 44.06280447]
 [ 0.94532537 -2.81425226 15.46962512]
 [ 1.13804516 -3.33577545 31.08643969]
 [ 0.63611217 -2.72980453 35.6825279 ]
 [ 1.09759067 -3.29847531 26.90534345]]
Mínimo alcanzado: [ 1.09759067 -3.29847531] con valor 26.90534344617208
GIF generado: descenso_rastrigin_2d.gif


**En 3 dimensiones**
  - Condiciones iniciales:
      - Coordenadas: Aleatoria
      - lrate (Tasa de aprendizaje): 0.01
      - Epoch (Iteraciones): 1000
      - Init_range (Rango de inicialización) : (-5.12, 5.12)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import imageio

# Función de Rastrigin
def rastrigin(point):
    """
    Calcula el valor de la función de Rastrigin.
    Args:
        point (array-like): Punto donde se evalúa la función.
    Returns:
        float: Valor de la función en el punto dado.
    """
    A = 10
    return A * len(point) + sum([(x**2 - A * np.cos(2 * np.pi * x)) for x in point])

# Derivada de la función de Rastrigin
def rastrigin_derivative(point):
    """
    Calcula el gradiente de la función de Rastrigin.
    Args:
        point (array-like): Punto donde se evalúa el gradiente.
    Returns:
        array: Gradiente de la función en el punto dado.
    """
    A = 10
    return np.array([2 * x + 2 * np.pi * A * np.sin(2 * np.pi * x) for x in point])

# Visualización en 3D con cuadro informativo
def visualize_rastrigin_3d(ai, iteration, filename=None):
    """
    Genera un gráfico en 3D mostrando la trayectoria del descenso por gradiente
    en la función de Rastrigin.
    Args:
        ai (list): Lista de puntos visitados durante el descenso.
        iteration (int): Iteración actual para mostrar en el gráfico.
        filename (str): Nombre del archivo si se quiere guardar la imagen.
    """
    ai = np.array(ai)
    trajectory_x = ai[:, 0]
    trajectory_y = ai[:, 1]
    trajectory_z = ai[:, 2]

    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')
    ax.plot3D(trajectory_x, trajectory_y, trajectory_z, color='red', label='Trayectoria')

    # Etiqueta del mínimo global
    ax.scatter3D(0, 0, 0, color='blue', label='Mínimo global', s=50)
    ax.text(0, 0, 0, '(0, 0, 0)', fontsize=10, color='blue')

    # Cuadro informativo
    text_str = (
        f"Iteración: {iteration}\n"
        f"Coordenadas: ({ai[-1, 0]:.2f}, {ai[-1, 1]:.2f}, {ai[-1, 2]:.2f})\n"
        f"Valor: {ai[-1, -1]:.4f}\n"
        f"Mínimo global: (0, 0, 0)"
    )
    plt.gcf().text(0.02, 0.85, text_str, fontsize=10, color='black', bbox=dict(facecolor='white', alpha=0.8))

    ax.set_title("Descenso por gradiente en la función de Rastrigin (3D)")
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.legend()

    if filename:
        plt.savefig(filename)
    plt.close()

# Función principal: Descenso por gradiente
def main():
    """
    Realiza el descenso por gradiente en la función de Rastrigin.
    """
    # Configuración de parámetros
    dimensions = 3  # Dimensiones: cambiar a 2 o 3
    lrate = 0.01  # Tasa de aprendizaje
    epoch = 1000  # Número de iteraciones
    init_range = (-5.12, 5.12)  # Rango para punto inicial

    # Generar punto inicial
    a = np.random.uniform(init_range[0], init_range[1], dimensions)
    print(f"Condición inicial: {a}")

    # Registrar los puntos visitados
    ai = []
    images = []

    for i in range(epoch):
        # Evaluar la función objetivo
        f = rastrigin(a)
        ai.append(np.append(a, f))

        # Calcular el gradiente y actualizar el punto
        grad = rastrigin_derivative(a)
        a = a - lrate * grad

        # Guardar imágenes para el GIF cada 10 iteraciones
        if i % 10 == 0:
            filename = f"rastrigin_iter_{i}.png"
            visualize_rastrigin_3d(ai, iteration=i, filename=filename)
            images.append(imageio.imread(filename))

        # Verificar convergencia
        if np.linalg.norm(grad) < 1e-6:
            print(f"Convergencia alcanzada en iteración {i}.")
            break

    ai = np.array(ai)

    # Resultados
    print("Últimos pasos:")
    print(ai[-10:, :])
    print(f"Mínimo alcanzado: {ai[-1, :-1]} con valor {ai[-1, -1]}")

    # Crear GIF
    imageio.mimsave('descenso_rastrigin.gif', images, fps=5, loop=0)
    print("GIF generado: descenso_rastrigin.gif")

if __name__ == '__main__':
    main()



Condición inicial: [-5.0270477  -0.2874339   4.87300159]


<ipython-input-10-80c186465844>:104: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  images.append(imageio.imread(filename))


Últimos pasos:
[[-2.75118360e+00  1.32210506e-01  2.81418359e+00  3.47638361e+01]
 [-3.32446108e+00 -3.34387689e-01  3.33581459e+00  6.69928877e+01]
 [-2.69717327e+00  2.14346736e-01  2.72992223e+00  4.70684621e+01]
 [-3.23725371e+00 -4.02559033e-01  3.29864928e+00  6.19159093e+01]
 [-2.54620404e+00 -3.34120954e-02  2.63348358e+00  4.99049048e+01]
 [-2.67513478e+00  9.81950440e-02  3.04814227e+00  3.32872230e+01]
 [-3.18170936e+00 -2.67296800e-01  2.80000645e+00  4.18684858e+01]
 [-2.54671514e+00  3.62660743e-01  3.34156488e+00  6.92988339e+01]
 [-2.67756804e+00 -1.21957256e-01  2.74756259e+00  4.20770848e+01]
 [-3.18838216e+00  3.16195550e-01  3.32085619e+00  5.58649927e+01]]
Mínimo alcanzado: [-3.18838216  0.31619555  3.32085619] con valor 55.864992667705906
GIF generado: descenso_rastrigin.gif
